/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentgrade;

import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author Paul Duan
 */
public class StudentGrade extends javax.swing.JFrame {

    /**
     * Creates new form StudentGrade
     */
    public StudentGrade() {
        //resize warning image to 16x16
        warning.setImage(warning.getImage().getScaledInstance(16, 16, 0));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        courseOneLabel = new javax.swing.JLabel();
        courseTwoLabel = new javax.swing.JLabel();
        courseThreeLabel = new javax.swing.JLabel();
        courseFourLabel = new javax.swing.JLabel();
        courseOneInput = new javax.swing.JTextField();
        courseTwoInput = new javax.swing.JTextField();
        courseThreeInput = new javax.swing.JTextField();
        courseFourInput = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        separator = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();
        warningLabel1 = new javax.swing.JLabel();
        warningLabel2 = new javax.swing.JLabel();
        warningLabel3 = new javax.swing.JLabel();
        warningLabel4 = new javax.swing.JLabel();
        warningLabel5 = new javax.swing.JLabel();
        warningLabel6 = new javax.swing.JLabel();
        courseOneAverage = new javax.swing.JLabel();
        courseTwoAverage = new javax.swing.JLabel();
        courseThreeAverage = new javax.swing.JLabel();
        courseFourAverage = new javax.swing.JLabel();
        calcCourseAverages = new javax.swing.JButton();
        calcStudentsAverages = new javax.swing.JButton();
        outOfBounds = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grade System");
        setIconImage(icon.getImage());
        setPreferredSize(new Dimension(656, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        titleLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 51, 204));
        titleLabel.setText("Students Grades");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(240, 0, 164, 30);

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name:");
        firstNameLabel.setFocusable(false);
        getContentPane().add(firstNameLabel);
        firstNameLabel.setBounds(10, 39, 90, 22);

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameLabel.setText("Last Name:");
        lastNameLabel.setFocusable(false);
        getContentPane().add(lastNameLabel);
        lastNameLabel.setBounds(329, 39, 89, 22);

        firstNameInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameInput.setForeground(new java.awt.Color(0, 51, 255));
        getContentPane().add(firstNameInput);
        firstNameInput.setBounds(110, 36, 184, 28);

        lastNameInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameInput.setForeground(new java.awt.Color(0, 51, 204));
        getContentPane().add(lastNameInput);
        lastNameInput.setBounds(432, 36, 185, 28);

        courseOneLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseOneLabel.setText("Course 1 Mark:");
        courseOneLabel.setFocusable(false);
        getContentPane().add(courseOneLabel);
        courseOneLabel.setBounds(10, 73, 93, 17);

        courseTwoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseTwoLabel.setText("Course 2 Mark:");
        courseTwoLabel.setFocusable(false);
        getContentPane().add(courseTwoLabel);
        courseTwoLabel.setBounds(329, 73, 93, 17);

        courseThreeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseThreeLabel.setText("Course 3 Mark:");
        courseThreeLabel.setFocusable(false);
        getContentPane().add(courseThreeLabel);
        courseThreeLabel.setBounds(10, 107, 93, 17);

        courseFourLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseFourLabel.setText("Course 4 Mark:");
        courseFourLabel.setFocusable(false);
        getContentPane().add(courseFourLabel);
        courseFourLabel.setBounds(329, 107, 93, 17);

        courseOneInput.setDocument(new studentgrade.MyPlainDocument("[^0-9.]"));
        courseOneInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(courseOneInput);
        courseOneInput.setBounds(110, 70, 105, 23);

        courseTwoInput.setDocument(new studentgrade.MyPlainDocument("[^0-9.]"));
        courseTwoInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(courseTwoInput);
        courseTwoInput.setBounds(432, 70, 106, 23);

        courseThreeInput.setDocument(new studentgrade.MyPlainDocument("[^0-9.]"));
        courseThreeInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(courseThreeInput);
        courseThreeInput.setBounds(110, 104, 105, 23);

        courseFourInput.setDocument(new studentgrade.MyPlainDocument("[^0-9.]"));
        courseFourInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(courseFourInput);
        courseFourInput.setBounds(432, 104, 106, 23);

        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.setFocusable(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(260, 140, 119, 25);

        separator.setText("==================================================================================");
        separator.setFocusable(false);
        getContentPane().add(separator);
        separator.setBounds(0, 164, 656, 14);

        infoTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        infoTable.setModel(model);
        infoTable.setRowHeight(20);
        infoTable.setSelectionBackground(new java.awt.Color(153, 204, 255));
        infoTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        infoTable.getTableHeader().setFont(new java.awt.Font("Tahoma", 0,14));
        infoTable.getTableHeader().setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        infoTable.getTableHeader().setReorderingAllowed(false);
        infoTable.setDefaultRenderer(Object.class, renderer);
        jScrollPane.setViewportView(infoTable);

        getContentPane().add(jScrollPane);
        jScrollPane.setBounds(10, 184, 630, 330);

        warningLabel1.setIcon(warning);
        warningLabel1.setFocusable(false);
        warningLabel1.setVisible(false);
        getContentPane().add(warningLabel1);
        warningLabel1.setBounds(298, 36, 21, 28);

        warningLabel2.setIcon(warning);
        warningLabel2.setFocusable(false);
        warningLabel2.setVisible(false);
        getContentPane().add(warningLabel2);
        warningLabel2.setBounds(621, 36, 30, 28);

        warningLabel3.setIcon(warning);
        warningLabel3.setFocusable(false);
        warningLabel3.setVisible(false);
        getContentPane().add(warningLabel3);
        warningLabel3.setBounds(219, 70, 16, 28);

        warningLabel4.setIcon(warning);
        warningLabel4.setFocusable(false);
        warningLabel4.setVisible(false);
        getContentPane().add(warningLabel4);
        warningLabel4.setBounds(542, 70, 16, 28);

        warningLabel5.setIcon(warning);
        warningLabel5.setFocusable(false);
        warningLabel5.setVisible(false);
        getContentPane().add(warningLabel5);
        warningLabel5.setBounds(219, 104, 16, 23);

        warningLabel6.setIcon(warning);
        warningLabel6.setFocusable(false);
        warningLabel6.setVisible(false);
        getContentPane().add(warningLabel6);
        warningLabel6.setBounds(542, 104, 16, 23);

        courseOneAverage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseOneAverage.setForeground(new java.awt.Color(51, 102, 255));
        courseOneAverage.setText("Course 1 Average Mark:");
        courseOneAverage.setFocusable(false);
        getContentPane().add(courseOneAverage);
        courseOneAverage.setBounds(10, 520, 260, 17);

        courseTwoAverage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseTwoAverage.setForeground(new java.awt.Color(51, 102, 255));
        courseTwoAverage.setText("Course 2 Average Mark:");
        courseTwoAverage.setFocusable(false);
        getContentPane().add(courseTwoAverage);
        courseTwoAverage.setBounds(10, 540, 260, 17);

        courseThreeAverage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseThreeAverage.setForeground(new java.awt.Color(51, 102, 255));
        courseThreeAverage.setText("Course 3 Average Mark:");
        courseThreeAverage.setFocusable(false);
        getContentPane().add(courseThreeAverage);
        courseThreeAverage.setBounds(10, 560, 260, 17);

        courseFourAverage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseFourAverage.setForeground(new java.awt.Color(51, 102, 255));
        courseFourAverage.setText("Course 4 Average Mark:");
        courseFourAverage.setFocusable(false);
        getContentPane().add(courseFourAverage);
        courseFourAverage.setBounds(10, 580, 260, 17);

        calcCourseAverages.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calcCourseAverages.setText("Course Averages");
        calcCourseAverages.setFocusable(false);
        calcCourseAverages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcCourseAveragesActionPerformed(evt);
            }
        });
        getContentPane().add(calcCourseAverages);
        calcCourseAverages.setBounds(270, 520, 150, 25);

        calcStudentsAverages.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calcStudentsAverages.setText("Students Averages");
        calcStudentsAverages.setFocusable(false);
        calcStudentsAverages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcStudentsAveragesActionPerformed(evt);
            }
        });
        getContentPane().add(calcStudentsAverages);
        calcStudentsAverages.setBounds(460, 520, 150, 25);

        outOfBounds.setForeground(new java.awt.Color(204, 0, 0));
        outOfBounds.setText("The Maxium Number of Students is 15!");
        outOfBounds.setVisible(false);
        getContentPane().add(outOfBounds);
        outOfBounds.setBounds(380, 150, 190, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Handle user's input

    public void inputHandle() {
        //no restriction for name
        firstName = firstNameInput.getText();
        lastName = lastNameInput.getText();
        if (firstName.equals("")) { //no input
            warningLabel1.setVisible(true); //show image
            flag = false;
        }
        if (lastName.equals("")) {
            flag = false;
            warningLabel2.setVisible(true);
        }

        try {
            course1 = Double.valueOf(courseOneInput.getText());
        } catch (NumberFormatException nfe) { //NumberFormatException
            flag = false;
            warningLabel3.setVisible(true);
        }
        try {
            course2 = Double.valueOf(courseTwoInput.getText());
        } catch (NumberFormatException nfe) {
            flag = false;
            warningLabel4.setVisible(true);
        }
        try {
            course3 = Double.valueOf(courseThreeInput.getText());
        } catch (NumberFormatException nfe) {
            flag = false;
            warningLabel5.setVisible(true);
        }
        try {
            course4 = Double.valueOf(courseFourInput.getText());
        } catch (NumberFormatException nfe) {
            flag = false;
            warningLabel6.setVisible(true);
        }
    }

    //add button
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //-----------Initialization-------------
        flag = true; //set flag
        warningLabel1.setVisible(false); //hide warning image
        warningLabel2.setVisible(false);
        warningLabel3.setVisible(false);
        warningLabel4.setVisible(false);
        warningLabel5.setVisible(false);
        warningLabel6.setVisible(false);
        outOfBounds.setVisible(false);
        //--------------End---------------------

        inputHandle();
        if (flag) { //no problem with the data
            try {
                studentsInfo[id][0] = id + 1; //set ID
                studentsInfo[id][1] = firstName; //set name
                studentsInfo[id][2] = lastName;
                studentsInfo[id][3] = course1; //set mark
                studentsInfo[id][4] = course2;
                studentsInfo[id][5] = course3;
                studentsInfo[id][6] = course4;
                id++;
            } catch (ArrayIndexOutOfBoundsException aiobe) {
                //Out of Bounds
                outOfBounds.setVisible(true);
            }

            model = new MyDefaultTableModel(studentsInfo, tableTitle); //update data model for Jtable
            infoTable.setModel(model);

            firstNameInput.setText(""); //After enter one student, clear input area
            lastNameInput.setText(""); //Because different students have differnet info
            courseOneInput.setText("");
            courseTwoInput.setText("");
            courseThreeInput.setText("");
            courseFourInput.setText("");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    //Calculate average mark for each course
    private void calcCourseAveragesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcCourseAveragesActionPerformed
        // TODO add your handling code here:
        Double course1Average = 0.0;
        Double course2Average = 0.0;
        Double course3Average = 0.0;
        Double course4Average = 0.0;

        //Traversal array and get each students'[3][4][5][6]
        for (int i = 0; i < id; i++) {
            course1Average += (double) studentsInfo[i][3];
            course2Average += (double) studentsInfo[i][4];
            course3Average += (double) studentsInfo[i][5];
            course4Average += (double) studentsInfo[i][6];
        }
        if (id != 0) { //if there is no infomation yet, then nothing will happen
            course1Average /= id; //get average and keep 2 decimal places
            courseOneAverage.setText("Course 1 Average Mark: " + String.format("%.2f", course1Average));

            course2Average /= id;
            courseTwoAverage.setText("Course 2 Average Mark: " + String.format("%.2f", course2Average));

            course3Average /= id;
            courseThreeAverage.setText("Course 3 Average Mark: " + String.format("%.2f", course3Average));

            course4Average /= id;
            courseFourAverage.setText("Course 4 Average Mark: " + String.format("%.2f", course4Average));
        }
    }//GEN-LAST:event_calcCourseAveragesActionPerformed
    
    //calculate each student's average mark on 4 courses
    private void calcStudentsAveragesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcStudentsAveragesActionPerformed
        // TODO add your handling code here:
        //Traversal array
        for (int i = 0; i < id; i++) {
            Double studentsAverage = 0.0;
            for (int ii = 3; ii < 7; ii++) { //get[3][4][5][6]
                studentsAverage += (double) studentsInfo[i][ii];
            }
            
            studentsInfo[i][7] = Double.valueOf(String.format("%.2f", studentsAverage / 4));
        }
        //update table model
        model = new MyDefaultTableModel(studentsInfo, tableTitle);
        infoTable.setModel(model);
        //set CellRenderer to repaint the border of last column
        infoTable.getColumn("Average").setCellRenderer(averagesCellRenderer);
    }//GEN-LAST:event_calcStudentsAveragesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGrade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton calcCourseAverages;
    private javax.swing.JButton calcStudentsAverages;
    private javax.swing.JLabel courseFourAverage;
    private javax.swing.JTextField courseFourInput;
    private javax.swing.JLabel courseFourLabel;
    private javax.swing.JLabel courseOneAverage;
    private javax.swing.JTextField courseOneInput;
    private javax.swing.JLabel courseOneLabel;
    private javax.swing.JLabel courseThreeAverage;
    private javax.swing.JTextField courseThreeInput;
    private javax.swing.JLabel courseThreeLabel;
    private javax.swing.JLabel courseTwoAverage;
    private javax.swing.JTextField courseTwoInput;
    private javax.swing.JLabel courseTwoLabel;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTable infoTable;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel outOfBounds;
    private javax.swing.JLabel separator;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel warningLabel1;
    private javax.swing.JLabel warningLabel2;
    private javax.swing.JLabel warningLabel3;
    private javax.swing.JLabel warningLabel4;
    private javax.swing.JLabel warningLabel5;
    private javax.swing.JLabel warningLabel6;
    // End of variables declaration//GEN-END:variables

    ImageIcon icon = new ImageIcon(StudentGrade.class.getResource("/studentgrade/Icon.png"));
    ImageIcon warning = new ImageIcon(StudentGrade.class.getResource("/studentgrade/Warning.png"));

    int id = 0;
    String firstName;
    String lastName;
    Double course1;
    Double course2;
    Double course3;
    Double course4;
    boolean flag = true; //if flag is true then add them into array, or show warning image.

    Object[][] studentsInfo = new Object[15][8];
    String[] tableTitle = {"ID", "First Name", "Last Name", "Course 1", "Course 2", "Course 3", "Course 4", "Average"};
    MyDefaultTableModel model = new MyDefaultTableModel(studentsInfo, tableTitle);
    MyDefaultTableCellRenderer renderer = new MyDefaultTableCellRenderer();
    MyAverageColumnRenderer averagesCellRenderer = new MyAverageColumnRenderer();
}
